image: docker:stable

variables:
  REV_VER: ultrahang/diaspora:0.7.10.0
  DOCKER_HOST: tcp://docker:2375

services:
- docker:dind

stages:
  - Build image
docker build:
  image: docker:stable
  stage: Build image
  script:
  - docker info
  - docker build -t $REV_VER .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push $REV_VER && docker image rm $REV_VER  

